import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useState } from "react";

const Login: NextPage = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState<boolean>(false);
  const router = useRouter();

  const handleLogin = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const allRegistrations = JSON.parse(
      localStorage.getItem("registrationData") || "[]"
    );

    // Check if any registration matches the entered email and password
    // const matchedRegistration = allRegistrations.find(
    //   (userData: any) =>
    //     userData.email === email && userData.password === password
    // );

    // if (matchedRegistration) {
    //   // Successful login, redirect or perform other actions
    //   router.push("/");
    // } else {
    //   console.error("Invalid credentials");
    // }

    const storedUserData = localStorage.getItem("registrationData");
    if (storedUserData) {
      const userData = JSON.parse(storedUserData);
      if (userData.email === email && userData.password === password) {
        router.push("/");
      } else {
        console.error("Invalid credentials");
      }
    } else {
      console.error("User not registered");
    }
  };
  const togglePasswordVisibility = (field: string) => {
    switch (field) {
      case "showPassword":
        setShowPassword(!showPassword);
        break;

      default:
        break;
    }
  };
  return (
    <>
      <Head>
        <title>Igralishte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="login-section" style={{ height: "100vh" }}>
        <div className="container py-5">
          <div className="row">
            <div className="col py-5">
              <Link href="/">
                <div className="logo-image"></div>
              </Link>
            </div>
          </div>
          <div className="row">
            <div className="col-12 d-flex flex-column align-items-center">
              <form className="mb-3" onSubmit={handleLogin}>
                <label htmlFor="email">Email адреса</label> <br />
                <input
                  onChange={(e) => setEmail(e.target.value)}
                  className="mb-3"
                  value={email}
                  type="email"
                  name="email"
                  id="email"
                  placeholder="example@example.com"
                />
                <label htmlFor="password">Лозинка</label> <br />
                <div className="password-input-container">
                  <input
                    className="mb-3"
                    id="password"
                    name="password"
                    type={showPassword ? "text" : "password"}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                  />
                  <span
                    className="password-toggle-icon"
                    onClick={() => togglePasswordVisibility("showPassword")}
                  >
                    {showPassword ? (
                      <i className="fa-regular fa-eye"></i>
                    ) : (
                      <i className="fa-regular fa-eye-slash"></i>
                    )}
                  </span>
                </div>
                <br />
                <p className="mb-3">
                  <a className="mb-3 forgot-pass" href="">
                    Ја заборави лозинката?
                  </a>
                </p>
                <button type="submit">Најави се</button>
              </form>
              <p className="text-center mb-3">или</p>
              <button className="socials-button mb-3">
                <span>
                  <i className="fa-solid fa-g"></i>
                </span>
                <span>Најави се преку Google</span>
              </button>
              <button className="socials-button mb-3">
                <span>
                  <i className="fa-brands fa-facebook"></i>
                </span>
                <span> Најави се преку Facebook</span>
              </button>
              <p className="npr text-center">
                Немаш профил?
                <Link href="/register">Регистрирај се</Link>
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Login;
