import { useEffect, useState } from "react";
import { GetServerSideProps, NextPage } from "next";
import React from "react";
import Registration from "../../components/Registration";
import RegistrationForm from "../../components/RegistrationForm";
import { ProductsType } from "../../types/types";
import Head from "next/head";

interface Props {
  data: ProductsType[];
}

const Register: NextPage<Props> = ({ data }) => {
  const [showRegistrationForm, setShowRegistrationForm] = useState(false);

  useEffect(() => {
    const registrationData = localStorage.getItem("registrationData");
    if (registrationData) {
      setShowRegistrationForm(true);
    }
  }, []);

  const handleShowRegistrationForm = () => {
    setShowRegistrationForm(true);
  };

  return (
    <>
      <Head>
        <title>Igralishte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!showRegistrationForm ? (
        <Registration onShowRegistrationForm={handleShowRegistrationForm} />
      ) : (
        <RegistrationForm data={data} />
      )}
    </>
  );
};

export default Register;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("http://localhost:5001/products/?_limit=3");
  const data: ProductsType[] = await res.json();

  return {
    props: { data },
  };
};
