import { NextPage } from "next";
import React from "react";
import Header from "../../components/header/Header";
import Footer from "../../components/footer/Footer";
import Head from "next/head";

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Igralishte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="contact-section">
        <Header />
        <div className="container py-3 mb-4">
          <div className="row mb-3">
            <div className="col-12">
              <p>
                <span className="mr-1">Почетна</span>

                <i className="fa-solid fa-angle-right"></i>

                <span className="ml-1">За Нас</span>
              </p>
            </div>
          </div>

          <div className="row mb-3">
            <div className="col d-flex align-items-center justify-content-center">
              <h2 className="us">Контакт</h2>
              <div className="us-image"></div>
            </div>
          </div>

          <div className="row mb-5">
            <div className="col rounded-image">
              <div className="rounded-image-inner rounded-image-inner-contact "></div>
            </div>
          </div>
          <div className="row">
            <div className="col-12 mb-4">
              <h2 className="we">Игралиште Дебар Маало</h2>
            </div>
            <div className="col-12 mb-4">
              <p className="desc-text text-center w-100">
                Откриј ги нашите останати модни парчиња и колекции кои ги немаме
                изложено на нашата страна!
              </p>
            </div>
            <div className="col-12 mb-4">
              <p className="adress-text w-100">
                Костурски Херои бр.6/14 Дебар Маало, Скопје
              </p>
            </div>
            <div className="col-12 contact mb-4">
              <h2>Телефон за контакт:</h2>
              <p className="text-center w-100">+ 389 078 380 406</p>
            </div>
            <div className="col-12 contact mb-5">
              <h2>Работно Време:</h2>
              <p className="text-center w-100">
                Понеделник - Петок 12:00 - 19:00
              </p>
              <p className="text-center w-100">Сабота 12:00 - 17:00</p>
            </div>
            <div className="col-12 text-center">
              <button>Кон продавницата</button>
            </div>
          </div>
        </div>

        <Footer />
      </section>
    </>
  );
};

export default Contact;
