import React, { useEffect, useState } from "react";
import { NextPage, GetServerSideProps } from "next";
import { useRouter } from "next/router";
import Header from "../../components/header/Header";
import Footer from "../../components/footer/Footer";
import BrandItem from "../../components/BrandItem";
import Pagination from "../../components/Pagination";
import { ProductsType } from "../../types/types";
import Card from "../../components/Card";
import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleRight } from "@fortawesome/free-solid-svg-icons";

interface BrandsPageProps {
  brandsData: ProductsType[];
  productsData: ProductsType[];
  currentPage: number;
  totalPages: number;
}

const BrandsPage: NextPage<BrandsPageProps> = ({
  brandsData,
  productsData,
}) => {
  const router = useRouter();
  const { brand, category } = router.query;

  const [currentPage, setCurrentPage] = useState(1);

  const productsPerPage = 10;

  const indexOfLastProduct = currentPage * productsPerPage;
  const indexOfFirstProduct = indexOfLastProduct - productsPerPage;
  const currentProducts = brandsData.slice(
    indexOfFirstProduct,
    indexOfLastProduct
  );

  const totalPages = Math.ceil(brandsData.length / productsPerPage);

  const handleNextPage = () => {
    setCurrentPage((prev) => Math.min(prev + 1, totalPages));
  };

  const handlePrevPage = () => {
    setCurrentPage((prev) => Math.max(prev - 1, 1));
  };

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  const headerBrand = brand ? brand : "";
  const headerCategory = category || "Сите";
  const filteredProducts = productsData.filter(
    (product) => product.brand === category
  );

  return (
    <>
      <Head>
        <title>Igralishte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container py-3 w-90">
        <div className="row mb-3">
          <div className="col-12">
            <p className="d-flex">
              {`Почетна`}
              {headerBrand ? (
                <span className="d-flex align-items-center">
                  <FontAwesomeIcon
                    style={{ height: "15px", width: "15px" }}
                    icon={faAngleRight}
                  />
                  {headerBrand}
                </span>
              ) : null}
              {headerCategory ? (
                <span className="d-flex align-items-center">
                  <FontAwesomeIcon
                    style={{ height: "15px", width: "15px" }}
                    icon={faAngleRight}
                  />
                  {headerCategory}
                </span>
              ) : null}
            </p>
          </div>
        </div>
        <div className="row py-4">
          <div className="col-12 d-flex  align-items-center">
            <div className="faq-sparks"></div>
            <h2 className="faq-header">{headerCategory}</h2>
          </div>
        </div>
        <div className="row">
          {currentProducts.map((item) => (
            <BrandItem key={item.id} {...item} />
          ))}
        </div>
        {filteredProducts.length > 0 ? (
          <div className="row my-3">
            <div className="col-12 py-5">
              <p className="other-brands">Парчиња од брендот:</p>
            </div>
            {filteredProducts.map((item, index) => (
              <Card index={index} key={item.id} {...item} />
            ))}
          </div>
        ) : null}
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          handlePageChange={handlePageChange}
          handlePrevPage={handlePrevPage}
          handleNextPage={handleNextPage}
        />
      </div>
      <Footer />
    </>
  );
};

export default BrandsPage;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  let brandsRes: Response;
  let productsRes: Response;

  if (query.category) {
    brandsRes = await fetch(
      `https://adventurous-jade-duck.cyclic.app/brands?q=${query.category}`
    );
    productsRes = await fetch(
      `https://adventurous-jade-duck.cyclic.app/products?q=${query.category}`
    );
  } else {
    brandsRes = await fetch("https://adventurous-jade-duck.cyclic.app/brands");
    productsRes = await fetch(
      "https://adventurous-jade-duck.cyclic.app/products"
    );
  }

  const brandsData: ProductsType[] = await brandsRes.json();
  const productsData: ProductsType[] = await productsRes.json();

  return {
    props: { brandsData, productsData },
  };
};
